package co.edu.usbcali.banco.modelo;
// Generated 25-jul-2017 23:40:32 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * CuentaRegistrada generated by hbm2java
 */
@Entity
@Table(name = "cuenta_registrada", schema = "public")
public class CuentaRegistrada implements java.io.Serializable {

	
	private long cureId;
	@NotNull(message="no valido")
	private Cliente cliente;
	@NotNull(message="no valido")
	private Cuenta cuenta;

	public CuentaRegistrada() {
	}

	public CuentaRegistrada(long cureId) {
		this.cureId = cureId;
	}

	public CuentaRegistrada(long cureId, Cliente cliente, Cuenta cuenta) {
		this.cureId = cureId;
		this.cliente = cliente;
		this.cuenta = cuenta;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)	  
	@Column(name = "cure_id", unique = true, nullable = false)
	public long getCureId() {
		return this.cureId;
	}

	public void setCureId(long cureId) {
		this.cureId = cureId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "clie_id")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cuen_id")
	public Cuenta getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Cuenta cuenta) {
		this.cuenta = cuenta;
	}

	public String toString(){
		return cureId+" "+cliente.getNombre()+" "+cuenta.getCuenId();
	}
}
