
-- Base de datos Indra
CREATE DATABASE indra;
--DDL
ALTER TABLE REGISTRO_CALCULO DROP CONSTRAINT FKREGISTRO_C836299;
DROP TABLE IF EXISTS REGISTRO_CALCULO CASCADE;
DROP TABLE IF EXISTS USUARIOS CASCADE;

CREATE TABLE REGISTRO_CALCULO (
  ID_RESULTADO    SERIAL NOT NULL, 
  RESULTADO       int4 NOT NULL, 
  FECHA_EJECUCION timestamp NOT NULL, 
  ID_USUARIO      int4 NOT NULL, 
  PRIMARY KEY (ID_RESULTADO));

CREATE TABLE USUARIOS (
  ID_Usuario SERIAL NOT NULL, 
  NAME       varchar(100) NOT NULL, 
  PRIMARY KEY (ID_Usuario));

ALTER TABLE REGISTRO_CALCULO ADD CONSTRAINT FKREGISTRO_C496761 FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID_Usuario);
LE REGISTRO_CALCULO ADD CONSTRAINT FKREGISTRO_C836299 FOREIGN KEY (USERID) REFERENCES USUARIOS (ID_Usuario);

-- DML
insert into usuarios(name) values('David');
insert into usuarios(name) values('Victoria');
insert into usuarios(name) values('Juan');
insert into usuarios(name) values('Paulina');

--SEGURITY

CREATE USER indra WITH PASSWORD 'indra';

GRANT INSERT,SELECT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO indra;

GRANT SELECT,USAGE ON ALL SEQUENCES IN schema public TO indra;
